import { PekerjaanCardProps, StatusPekerjaanProps } from "./interface";

export const pekerjaanCategories = [
  {
    category: "Home Service",
    subCategories: ["Cleaning Service", "Rennovation", "Home Service"],
  },
  {
    category: "Vehicle Service",
    subCategories: ["Car Wash", "Tune Up"],
  },
];

export const pekerjaanCards: PekerjaanCardProps[] = [
  {
    id: "1",
    subCategory: "Cleaning Service",
    assignner: "John Doe",
    todoDate: new Date(),
    createdAt: new Date(),
    price: 1000000,
  },
  {
    id: "2",
    subCategory: "Home Service",
    assignner: "John Doe",
    todoDate: new Date(),
    createdAt: new Date(),
    price: 2000000,
  },
  {
    id: "3",
    subCategory: "Rennovation",
    assignner: "John Doe",
    todoDate: new Date(),
    createdAt: new Date(),
    price: 3000000,
  },
  {
    id: "4",
    subCategory: "Cleaning Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 1)),
    createdAt: new Date(),
    price: 1500000,
  },
  {
    id: "5",
    subCategory: "Home Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 1)),
    createdAt: new Date(),
    price: 2500000,
  },
  {
    id: "6",
    subCategory: "Rennovation",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 1)),
    createdAt: new Date(),
    price: 3500000,
  },
  {
    id: "7",
    subCategory: "Cleaning Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 2)),
    createdAt: new Date(),
    price: 1200000,
  },
  {
    id: "8",
    subCategory: "Home Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 2)),
    createdAt: new Date(),
    price: 2200000,
  },
  {
    id: "9",
    subCategory: "Rennovation",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 2)),
    createdAt: new Date(),
    price: 3200000,
  },
  {
    id: "10",
    subCategory: "Cleaning Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    createdAt: new Date(),
    price: 1300000,
  },
  {
    id: "11",
    subCategory: "Home Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    createdAt: new Date(),
    price: 2300000,
  },
  {
    id: "12",
    subCategory: "Rennovation",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    createdAt: new Date(),
    price: 3300000,
  },
  {
    id: "13",
    subCategory: "Cleaning Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 4)),
    createdAt: new Date(),
    price: 1400000,
  },
  {
    id: "14",
    subCategory: "Home Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 4)),
    createdAt: new Date(),
    price: 2400000,
  },
  {
    id: "15",
    subCategory: "Rennovation",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 4)),
    createdAt: new Date(),
    price: 3400000,
  },
  {
    id: "16",
    subCategory: "Cleaning Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 5)),
    createdAt: new Date(),
    price: 1100000,
  },
  {
    id: "17",
    subCategory: "Home Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 5)),
    createdAt: new Date(),
    price: 2100000,
  },
  {
    id: "18",
    subCategory: "Rennovation",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 5)),
    createdAt: new Date(),
    price: 3100000,
  },
  {
    id: "19",
    subCategory: "Cleaning Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 6)),
    createdAt: new Date(),
    price: 1600000,
  },
  {
    id: "20",
    subCategory: "Home Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 6)),
    createdAt: new Date(),
    price: 2600000,
  },
];

export const statusPekerjaanCards: StatusPekerjaanProps[] = [
  {
    id: "1",
    subCategory: "Cleaning Service",
    assignner: "John Doe",
    todoDate: new Date(),
    createdAt: new Date(),
    price: 1000000,
    status: "Menunggu Pekerja Berangkat",
  },
  {
    id: "2",
    subCategory: "Home Service",
    assignner: "John Doe",
    todoDate: new Date(),
    createdAt: new Date(),
    price: 2000000,
    status: "Menunggu Pekerja Berangkat",
  },
  {
    id: "3",
    subCategory: "Rennovation",
    assignner: "John Doe",
    todoDate: new Date(),
    createdAt: new Date(),
    price: 3000000,
    status: "Tiba Di Lokasi",
  },
  {
    id: "4",
    subCategory: "Cleaning Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 1)),
    createdAt: new Date(),
    price: 1500000,
    status: "Tiba Di Lokasi",
  },
  {
    id: "5",
    subCategory: "Home Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 1)),
    createdAt: new Date(),
    price: 2500000,
    status: "Melakukan Pelayanan Jasa",
  },
  {
    id: "6",
    subCategory: "Rennovation",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 1)),
    createdAt: new Date(),
    price: 3500000,
    status: "Melakukan Pelayanan Jasa",
  },
  {
    id: "7",
    subCategory: "Cleaning Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 2)),
    createdAt: new Date(),
    price: 1200000,
    status: "Selesai",
  },
  {
    id: "8",
    subCategory: "Home Service",
    assignner: "John Doe",
    todoDate: new Date(new Date().setDate(new Date().getDate() + 2)),
    createdAt: new Date(),
    price: 2200000,
    status: "Selesai",
  },
];

export const statusPekerjaan = [
  "Menunggu Pekerja Berangkat",
  "Tiba Di Lokasi",
  "Melakukan Pelayanan Jasa",
  "Selesai",
];
